ALTER TABLE "Pricing"
ADD COLUMN IF NOT EXISTS "fetiraBasePrice" DOUBLE PRECISION NOT NULL DEFAULT 120,
ADD COLUMN IF NOT EXISTS "fetiraExtraEggPrice" DOUBLE PRECISION NOT NULL DEFAULT 30,
ADD COLUMN IF NOT EXISTS "donut2PairPackagePrice" DOUBLE PRECISION NOT NULL DEFAULT 120,
ADD COLUMN IF NOT EXISTS "donut4PairPackagePrice" DOUBLE PRECISION NOT NULL DEFAULT 220,
ADD COLUMN IF NOT EXISTS "donut6PairPackagePrice" DOUBLE PRECISION NOT NULL DEFAULT 320,
ADD COLUMN IF NOT EXISTS "fetiraBaseCost" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS "fetiraExtraEggCost" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS "donut2PairPackageCost" DOUBLE PRECISION NOT NULL DEFAULT 90,
ADD COLUMN IF NOT EXISTS "donut4PairPackageCost" DOUBLE PRECISION NOT NULL DEFAULT 170,
ADD COLUMN IF NOT EXISTS "donut6PairPackageCost" DOUBLE PRECISION NOT NULL DEFAULT 250;